import Router from "express";
export const quizRouter = Router();
import { Validate } from "../middlewares/validator.js";
import { asyncHandler } from "../utils/asyncWrapper.js";
import { createQuizSchema, updateQuizSchema, checkQuizSchema } from "@common/contracts";
import { checkQuiz, createQuiz, deleteQuiz, liveQuiz, testQuiz } from "../controllers/quiz-controller.js";
import { auth } from "../middlewares/auth.js";
quizRouter.use(auth);
quizRouter.post("/", Validate(createQuizSchema), asyncHandler(createQuiz));
quizRouter.put("/live", asyncHandler(liveQuiz));
quizRouter.delete("/:id", asyncHandler(deleteQuiz));
quizRouter.post("/check", Validate(checkQuizSchema), asyncHandler(checkQuiz));
quizRouter.post("/test", asyncHandler(testQuiz));
